dvpOAuth/__init__.py,sha256=IY0d8jGF_8115n6Fr_8tuDwiPknFTHVkhkQAyGQNtEM,162
dvpOAuth/class_OAuth.py,sha256=Rn7wA8UYhDglKMcAzJIDa5PH63zZKrHdMMuMCW5uiVo,44454
dvpOAuth/error.py,sha256=Y3BjsevsSGMDVVdn6ztiQMcGNtB6lySkNPoL7y4BT-Q,131
dvpOAuth/util.py,sha256=y-S4zD5BGEWKHVfJKGyy5teIeV2XdWrMXeRubAW54Ek,685
dvpOAuth-0.0.1.dist-info/LICENSE,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
dvpOAuth-0.0.1.dist-info/METADATA,sha256=64f5JJ-XLZZFiOPyvCDKtidX1QThpkiExwvadtw4k70,1024
dvpOAuth-0.0.1.dist-info/WHEEL,sha256=2wepM1nk4DS4eFpYrW1TTqPcoGNfHhhO_i5m4cOimbo,92
dvpOAuth-0.0.1.dist-info/top_level.txt,sha256=14UgmlstFHh0UvlWIljRlFO26u2OesXzFC8SsWFZRmw,9
dvpOAuth-0.0.1.dist-info/RECORD,,
