dvpOAuth/__init__.py,sha256=_hXxJlqrBq3HyArApvAtsBtbyrQzshNChcLOm4e4V2s,162
dvpOAuth/class_OAuth.py,sha256=s6usEO2TAF3AZY1HRO1OC1vHSCF4P0JDCnaUXklKpDI,44490
dvpOAuth/error.py,sha256=Y3BjsevsSGMDVVdn6ztiQMcGNtB6lySkNPoL7y4BT-Q,131
dvpOAuth/util.py,sha256=y-S4zD5BGEWKHVfJKGyy5teIeV2XdWrMXeRubAW54Ek,685
dvpOAuth-0.0.2.dist-info/LICENSE,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
dvpOAuth-0.0.2.dist-info/METADATA,sha256=hp5C119-I-Sgv3w3JosTzephkDbMTqVGvWhneeoMalc,1024
dvpOAuth-0.0.2.dist-info/WHEEL,sha256=2wepM1nk4DS4eFpYrW1TTqPcoGNfHhhO_i5m4cOimbo,92
dvpOAuth-0.0.2.dist-info/top_level.txt,sha256=14UgmlstFHh0UvlWIljRlFO26u2OesXzFC8SsWFZRmw,9
dvpOAuth-0.0.2.dist-info/RECORD,,
